# -*- coding: utf-8 -*-
"""05_PB_DataStructre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DTgEC1kpKrOeJhTesrMtZDG518V2EDb
"""

#1 Problem 1 — Sum of List
#1 Find sum of all elements.
a = [10, 20, 30, 40]
sum =0
for i in a:
  sum =sum+i
print(sum)

# 2 find maxium Without using max().
a = [4,7,2,9,1]

# Handle an empty list case
if not a:
    maxium = None # Or raise an error, depending on desired behavior for empty lists
else:
    maxium = a[0] # Initialize maxium with the first element of the list
    i = 1 # Start iterating from the second element
    leng = len(a)
    while i < leng:
      if a[i] > maxium: # Compare the current element with the current maximum
        maxium = a[i] # Update maxium if a larger element is found
      i = i + 1 # Increment the loop counter to move to the next element

print(maxium)

# 3 Without using reverse().
a = [1,2,3,4,5]
a.sort(reverse =True)
print(a)

# 4 Count Even Numbers
count =0
a = [1,2,3,4,5,6,7]
for i in a:
  if i%2==0:
    count +=1
print(count)

# 5 Squares Using List Comprehension
li =[1,4,9,16,25]
new=[x*x for x in li]
print(new)

# 6 Extract Even Numbers
li = [10,15,20,25,30]
new =[]
for i in li:
  if i%2 ==0:
    new.append(i)
print(new)

# 7 Remove Negative Numbers
a = [3,-1,5,-7,9]
aa=[]

for i in a:
  if i >0:
    aa.append(i)

print(aa)

#8 Remove Duplicates
a = [1,2,2,3,4,4,5]
uniq=set(a)
print(uniq)

# 9 Common Elements
A = [1,2,3,4]
B = [3,4,5,6]

# Convert lists to sets to find common elements
set_A = set(A)
set_B = set(B)
common_elements = set_A & set_B # Or set_A.intersection(set_B)
print(list(common_elements)) # Convert back to list for output if desired

#Unique Characters
s = "datascience"
a =set("datascience")
print(a)

# Print Keys & Values
student = {
    "name":"Asha",
    "marks":90,
    "city":"Chennai"
}
for key,value in student.items():
  print(key,value)

# Frequency Count
aa = [1,1,2,3,2,1,4]
dic={}
for a in aa:
  if a in dic:
    dic[a]=dic[a]+1
  else:
    dic[a]=1
print(dic)

# Word Count
s = "data science is fun data"

words = s.split()

dic = {}

for w in words:
    if w in dic:
        dic[w] += 1
    else:
        dic[w] = 1

print(dic)

#Sort Dictionary by Value
d = {"a":3,"b":1,"c":2}

# Sort dictionary items by value using sorted() and a lambda function
sorted_items = sorted(d.items(), key=lambda item: item[1])

# Convert the sorted items (list of tuples) back to a dictionary
# Note: For Python versions < 3.7, dictionary order is not guaranteed.
sorted_d = dict(sorted_items)

print(sorted_d)

# Find Highest Value in Dictionary
marks = {
    "A":78,
    "B":92,
    "C":85
}

# Corrected: Use .values() to get dictionary values and then find the maximum
highest_value = max(marks.values())
print(highest_value)

#Merge Two Dictionaries
d1 = {"a":1,"b":2}
d2 = {"c":3,"d":4}
merged_dict = {**d1, **d2}
print(merged_dict)

#Nested Dictionary Access
students = {
 "s1":{"name":"Ram","marks":80},
 "s2":{"name":"Sam","marks":90}
}
for key,value in students.items():
  print(key,value)

#Most Frequent Element
a = [2,3,2,4,5,2,3]
dic ={}
for i in a:
  if i in dic:
    dic[i] =dic[i]+1
  else:
    dic[i]=1
m =max(dic.values())  # or m =max(dic,key=dic.get()) print(m)
x=dic.get(m)
print(x)

#Group Students by Marks
data = [
('A',90),
('B',80),
('C',90)
]
dic ={}
for value,key in data:
  if key in dic:
    dic[key].append(value) # Append to existing list
  else:
    dic[key]=[value] # Initialize with a list containing the first value
print(dic)

#Remove Duplicate Dictionary Records
data = [
 {"id":1,"name":"A"},
 {"id":1,"name":"A"},
 {"id":2,"name":"B"}
]

dic = {}

for d in data:
    dic[d["id"]] = d

print(list(dic.values()))