# -*- coding: utf-8 -*-
"""patterens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eY1ogC59yC5Nx4QMoivIzSc1T3i7pFhA
"""

#Diagnol(Right)
n =7
for i in range(7):
  for j in range(7):
    if i ==j:
      print("*",end="")
    else:
      print(" ",end ="")
  print()

#Diagnol(Left)
n =6
for i in range(7):
  for j in range(7):
    if i+j==n-1:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#half part
n =7
for i in range(7):
  for j in range(7):
    if j ==n-1 and i>2 and 3*n/4:
      print("*",end="")
    else:
      print(" ",end ="")
  print()

#lower left triangle including triangle with diagnol
n=6
for i in range(n):
  for j in range(n):
    if i-j>=0:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#Upper right  triangle including triangle with diagnol
n=6
for i in range(n):
  for j in range(n):
    if i-j<=0:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#lower left triangle including triangle without diagnol
n=6
for i in range(n):
  for j in range(n):
    if i-j>0:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#Upper right  triangle including triangle  without diagnol
n=6
for i in range(n):
  for j in range(n):
    if i-j<0:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#Lower right triagle including triangle with diagnol
n=6
for i in range(n):
  for j in range(n):
    if i+j >=n-1:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#Lower right triagle including triangle with diagnol
n=6
for i in range(n):
  for j in range(n):
    if i+j <=n-1:          #for without diagnol just remove = symbol
      print("*",end="")
    else:
      print(" ",end="")
  print()

# without diagnol
n=10
for i in range(n):
  for j in range(n):
    if i+j >n-1 or i+j<n-1:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#middle line(vertical)
n=10
for i in range(n):
  for j in range(n):
    if j==n/2:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#middle line (horizontal)
n=10
for i in range(n):
  for j in range(n):
    if i==n/2:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#Diagnol crossing
n=10
for i in range(n):
  for j in range(n):
    if  i==j  or i+j==n-1:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#i+j ==n/2
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0  or i+j==n/2:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#square middle star
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0  or i/2==j/2:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#square middle star
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0 or i-j ==n/2:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#square middle star
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0 or i-j == (-(n/2)):
      print("*",end="")
    else:
      print(" ",end="")
  print()

#square middle star
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0 or i+j ==n/2 or i+j == 3*n/2 or i-j ==-n/2 or i-j ==n/2 or i==n/2 or j ==n/2 :
      print("*",end="")
    else:
      print(" ",end="")
  print()

#square middle star
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0 or i+j ==n/2 or i+j == 3*n/2 or i-j ==-n/2 or i-j ==n/2 or i==n/2 or j ==n/2 or i == n/4 or i ==3*n/4 or j ==n/4 or j == 3*n/4 :
      print("*",end="")
    else:
      print(" ",end="")
  print()



#square middle star
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0 or i+j ==n/2 or i+j == 3*n/2 or i-j ==-n/2 or i-j ==n/2 or i ==n//2 and j == n//2 :
      print("*",end="")
    else:
      print(" ",end="")
  print()

#square middle star
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0 or i+j ==n/2 or i+j == 3*n/2 or i-j ==-n/2 or i-j ==n/2 or i ==n/2:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#square middle star
n=10
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0 or i+j ==n/2 or i+j == 3*n/2 or i-j ==-n/2 or i-j ==n/2 or i ==n/2 or j ==n/2:
      print("*",end="")
    else:
      print(" ",end="")
  print()

#square middle star
n=50
for i in range(n):
  for j in range(n):
    if i==0 or j ==n-1 or i ==n-1 or j ==0 or i+j ==n/2 or i+j == 3*n/2 or i-j ==-n/2 or i-j ==n/2 or i ==n/2 or i==n//4 or i == 3*n//4 or j ==n//2 or j == n//4 or j== 3*n//4:
      print("*",end="")
    else:
      print(" ",end="")
  print()

n = 7

for i in range(n):

    # -------- V --------
    for j in range(n):
        if (j == i and i <= n//2) or (j == n-1-i and i <= n//2) \
           or (i > n//2 and j == n//2):
            print("*", end="")
        else:
            print(" ", end="")
    print("  ", end="")

    # -------- A --------
    for j in range(n):
        if i == 0 or i == n//2 or j == 0 or j == n-1:
            print("*", end="")
        else:
            print(" ", end="")
    print("  ", end="")

    # -------- R --------
    for j in range(n):
        if (j == 0 or
            i == 0 or
            i == n//2 or
            (j == n-1 and i < n//2) or
            (i - j == n//2)):
            print("*", end="")
        else:
            print(" ", end="")
    print("  ", end="")

    # -------- S --------
    for j in range(n):
        if (i == 0 or i == n//2 or i == n-1 or
            (j == 0 and i < n//2) or
            (j == n-1 and i > n//2)):
            print("*", end="")
        else:
            print(" ", end="")
    print("  ", end="")

    # -------- H --------
    for j in range(n):
        if j == 0 or j == n-1 or i == n//2:
            print("*", end="")
        else:
            print(" ", end="")
    print("  ", end="")

    # -------- I --------
    for j in range(n):
        if i == 0 or i == n-1 or j == n//2:
            print("*", end="")
        else:
            print(" ", end="")
    print("  ", end="")

    # -------- N --------
    for j in range(n):
        if j == 0 or j == n-1 or i == j:
            print("*", end="")
        else:
            print(" ", end="")
    print("  ", end="")

    # -------- I --------
    for j in range(n):
        if i == 0 or i == n-1 or j == n//2:
            print("*", end="")
        else:
            print(" ", end="")
    print()