# -*- coding: utf-8 -*-
"""Numpy1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O23GfAU4UvwRseZw2n8wKoB2oJ27OQ32
"""

'''NumPy = Numerical Python

It is used for:

Fast numerical calculations

Working with large datasets

Base of Pandas, ML, AI

:: Why NumPy is Fast

Homogeneous data (same datatype)

Stored in contiguous memory

Written in C internally

Uses vectorized operations (no Python loops)'''

#creating array
#1 from list
import numpy
import numpy as np
aar =np.array([1,9,4])
aar

#2 from zero
import numpy as np
np.zeros([2,2])

# 3 from one
np.ones((3,8))

#4 identity
np.eye(4,3)

# 5 range
np.arange(1,10,2)

#6.linspace
np.linspace(1,10,6)#give 6 number between 1 and includding 10 with constant differance'
#every output differance is constant

#importent properties shape,ndim,size,dtype
#1.shape
arr1 =np.array([[1,2,3],
       [5,6,8]])

arr1.shape

# 2.dimension
arr1.ndim

# 3,type
arr1.dtype

# 4.size  ,it give total no elements
arr1.size

#Indexing & Slicing
arr = np.array([10,20,30,40,50])
arr

arr[0]
arr[-1]
arr[0:3]     # 10,20,30
arr[:3]      # same
arr[::2]     # 10,30,50m

#2D slicing
arr7= np.array([[1,2,3],
                [4,5,6]])
arr7

arr7[0,1]     # row 0 col 1

arr7[:,1]     # full column 1

arr7[1,:]     # full row 1

#🚀 Step 4: Vectorized Operations
arr = np.array([10,20,30])

arr+5

arr-5

arr*5

a = np.array([1,2,3])
b = np.array([4,5,6])

a + b

a*b

#🚀 Step 5: Boolean Indexing
arr = np.array([10,20,30,40,50])
#get element >25
arr[arr > 25]

arr = np.array([10,20,30,40,50])
#replace #get element >25 =100
arr[arr > 25] = 100
print(arr)

#🚀 Step 6: Axis Concept
a = np.array([[1,2,3],
              [4,5,6]])
print(a)

np.sum(a,axis =0) #coloum

np.sum(a,axis=1)

#Reshape and Resize
arr = np.array([1,2,3,4,5,6])
arr.resize(2,3)

arr.reshape(2,3) #returns new array

arr.resize(2,3)# change the orginal array
print(arr)

# creation of array it is not default
#we use list/tuple and convert into array

import numpy
ar1 =numpy.array([1,23,4])
ar1

a = np.array([1,2,3])
b = 5
print(a + b)

lsit =[1,"var"]
lsit #list can have different datatype but in  array we cannot

ar2 =numpy.array([1,"var"])
ar2   #here answer everything in string because string>complex>float>int>bool

lsit

#sqauring number in list
list =[1,2,3]
q =[x*x for x in list]
print(q)

#in array i can  square very easily
import numpy
ar1 =numpy.array([1,23,4])

ar1
ar1 **2

import numpy
import numpy as np
np.zeros([3,4])

np.random.random([3,4])#shape parameter

np.full([3,4],10)#shape ,value

np.full([2,2],"a")

range(1,5)

for i in range(1,5):
  print(i)

__builtins__.list(range(1,5))

__builtins__.list(range(1,10,2))

np.arange(1,10,2)#here we get array in directely output

#linspace
np.linspace(1,10,6)#give 6 number between 1 and includding 10 with constant differance'
#every output differance is constant

#Array inspection
print(w)

arr1 =np.arange(1,25)
arr1

arr1.size#to find size
arr1.dtype
arr1

arr1.dtype
#type

#dimension
arr1.ndim

arr2 =arr1.reshape(6,4)#as my arr1 contain 24 your give range should (12,2),(6,4)
arr2

arr2.ndim

arr3=arr1.reshape(3,2,4)#3 array with 2 rows and 4 coloum
arr3

arr3.ndim#how many square brackets that many dimension

arr = np.array([10,20,30,40,50])
q =[i for i in arr if i>25]
w =[100 for i in arr if i>25]
q
w