# -*- coding: utf-8 -*-
"""1_hands_on.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhrkMJBn_ZmORr38ejMqw7z6uCxiO7mX
"""

#matrix addition
import numpy as np
a1=np.array([[1,3],[2,4]])
a2=np.array([[3,4],[4,5]])
a1+a2

#Subtraction
a1-a2

#normal multiplication
a1*a2

#hamans multiplication
a1@a2

#Rank of the matrix
rank=np.linalg.matrix_rank([[1,2],[2,4]]) #i beacause 2 is dervied from 1
rank

#Find the determinate

determinate=np.linalg.det(a1)
determinate

#TO find the inverse
Inverse=np.linalg.inv(a1)
Inverse

#Transpose
import numpy as np
a1=np.array([[1,3],[2,4]])

a2=np.array([[3,4],[4,5]])
tran=np.transpose(a1)
print(tran)

a1.T