# -*- coding: utf-8 -*-
"""Merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfIIHOUfo0VN4yKuEoFwdQGBxMdeNuXq
"""

n, m = map(int, input().split())

lis1 = list(map(int, input().split()))
lis2 = list(map(int, input().split()))

i = 0
j = 0
res = []

while i < n and j < m:
    if lis1[i] < lis2[j]:
        res.append(lis1[i])
        i += 1
    else:
        res.append(lis2[j])
        j += 1

while i < n:
    res.append(lis1[i])
    i += 1

while j < m:
    res.append(lis2[j])
    j += 1

print(*res)