# -*- coding: utf-8 -*-
"""Crosspro_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6P6wXJjIdg3qzJOOgODiaubTCmslIil

NumPy handles everything internally.
1)It takes two vectors
2) Applies cross product formula
3) Returns a new vector perpendicular to both
np.cross(A, B)
"""

#Vector must be 3D
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
#NumPy allows 2D, but:It assumes the 3rd value = 0
A = np.array([1, 2]) #output -2 scalar

#Order matters
np.cross(A, B) ≠ np.cross(B, A) #oppsite direction

#Input shape must match
A = np.array([1,2,3])
B = np.array([4,5,6])
#wrong
A = np.array([1,2,3])
B = np.array([[4,5,6],[7,8,9]])

#Axis
A = np.array([[1,2,3],
              [4,5,6]])
#Each row = one vector
np.cross(A, B,axis=0)